Unifies input parameter checking across all scripts

diff --git a/utilities/scripts/dockerhub_count_pulls b/utilities/scripts/dockerhub_count_pulls
--- a/utilities/scripts/dockerhub_count_pulls
+++ b/utilities/scripts/dockerhub_count_pulls
@@ -7,13 +7,16 @@ display_usage() {
 } 
 
 if [[ $1 == "--help" ]]; then
-  display_usage
-  exit 1
+    display_usage
+    exit 0
 fi
 
-if [ $# -lt 1 ]; then
-  display_usage
-  exit 0
+if [ $# -lt 1 ] && [ $# -gt 3 ]; then
+    tput setaf 1
+    echo -e "Error. This script requires one, two or three arguments.\n"
+    tput sgr0
+    display_usage
+    exit 1
 fi
 
 USER=$1
@@ -39,8 +42,10 @@ esac
 done
 
 if ! [ -x "$(command -v $JQ)" ]; then
-  echo "The jq executable is not available: $JQ"
-  exit 1
+    tput setaf 1
+    echo -e "Error. The jq executable is not available: $JQ.\n"
+    tput sgr0
+    exit 1
 fi
 
 NEXT="https://hub.docker.com/v2/repositories/$USER/?page_size=$PAGE_SIZE"
diff --git a/utilities/scripts/dockerhub_list_repo_with_tags b/utilities/scripts/dockerhub_list_repo_with_tags
--- a/utilities/scripts/dockerhub_list_repo_with_tags
+++ b/utilities/scripts/dockerhub_list_repo_with_tags
@@ -1,19 +1,22 @@
 #!/bin/bash
 
 display_usage() {
-  echo -e "This script lists the tags for a given Docker Hub repository (user/image)."
-  echo -e "\nUsage:"
-  echo -e "\tUsage: `basename $0` <docker-hub-repository> [-jq=</path/to/jq>]"
+    echo -e "This script lists the tags for a given Docker Hub repository (user/image)."
+    echo -e "\nUsage:"
+    echo -e "\tUsage: `basename $0` <docker-hub-repository> [-jq=</path/to/jq>]"
 }
 
 if [[ $1 == "--help" ]]; then
-  display_usage
-  exit 1
+    display_usage
+    exit 0
 fi
 
-if [ $# -lt 1 ]; then
-  display_usage
-  exit 0
+if [ $# -lt 1 ] && [ $# -gt 2 ]; then
+    tput setaf 1
+    echo -e "Error. This script requires one or two arguments.\n"
+    tput sgr0
+    display_usage
+    exit 1
 fi
 
 REPOSITORY=$1
@@ -34,8 +37,10 @@ esac
 done
 
 if ! [ -x "$(command -v $JQ)" ]; then
-  echo "The jq executable is not available: $JQ"
-  exit 1
+    tput setaf 1
+    echo -e "Error. The jq executable is not available: $JQ.\n"
+    tput sgr0
+    exit 1
 fi
 
 item=${REPOSITORY}
